-- MySQL Script generated by MySQL Workbench
-- Sat Jan 13 14:41:40 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema nhatky
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema nhatky
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `nhatky` DEFAULT CHARACTER SET utf8 ;
USE `nhatky` ;

-- -----------------------------------------------------
-- Table `nhatky`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nhatky`.`users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(100) NULL,
  `name` VARCHAR(255) NULL,
  `phone` VARCHAR(13) NULL,
  `role` TINYINT(1) NULL,
  `point` INT NOT NULL,
  `status` TINYINT(1) NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nhatky`.`diaries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nhatky`.`diaries` (
  `diary_id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NULL,
  `content` LONGTEXT NULL,
  `start_day` DATETIME NULL,
  `end_day` DATETIME NULL,
  `create_day` DATETIME NULL,
  `last_day` DATETIME NULL,
  `status` TINYINT(1) NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`diary_id`),
  INDEX `fk_diaries_users_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_diaries_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `nhatky`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nhatky`.`achievements`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nhatky`.`achievements` (
  `achievement_id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NULL,
  `content` LONGTEXT NULL,
  `status` TINYINT(1) NULL,
  `point` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`achievement_id`),
  INDEX `fk_achievement_users1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_achievement_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `nhatky`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nhatky`.`members`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nhatky`.`members` (
  `user_id` INT NOT NULL,
  `status` TINYINT(1) NULL,
  `diary_id` INT NOT NULL,
  INDEX `fk_members_users1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_members_diaries1_idx` (`diary_id` ASC) VISIBLE,
  CONSTRAINT `fk_members_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `nhatky`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_members_diaries1`
    FOREIGN KEY (`diary_id`)
    REFERENCES `nhatky`.`diaries` (`diary_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
